# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ctse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3004
  selector:
    app: cart-service
