# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ctse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: product-service
