# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ctse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3005
  selector:
    app: order-service
