# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ctse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3002
  selector:
    app: user-service
